### PR TITLE
115 fix validation for bid

### LINKED ISSUE #115: Fix validation for bid
User should be able to have bids with the same amount of different items. Right now you can only bid a certain price once, regardless of the item.

### PR DESCRIPTION
**Pull request by saylerb**
I added a item scope to bidding, so now bidding should actually work correctly.

closes #115

### CODE REVIEW

File: app/models/bid.rb [hunk 1]
```diff
@@ -7,6 +7,6 @@ class Bid < ActiveRecord::Base
   validates :price, presence: :true
 
   validates_uniqueness_of :price,
-                          scope: :user_id,
+                          scope: [:user_id, :item_id],
```
Comment (ErinGreenhalgh) [inline app/models/bid.rb:10]: nice fix

File: app/views/items/show.html.erb [hunk 2]
```diff
@@ -14,7 +14,7 @@
         No current bids
       </p>
       <% else %>
-        Highest Bid: <%= @item.high_bid %><br>
+        Highest Bid: <%= number_to_currency(@item.high_bid) %><br>
```
Comment (ErinGreenhalgh) [inline app/views/items/show.html.erb:17]: nice helper. does the method definition show up in another commit? or is it already on dev?

Comment (saylerb) [inline app/views/items/show.html.erb:17]: The number_to_currency helper is built into Rails!  It's a method in the ActionView class, which is a class available to views in Rails:

http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html
